### ISSUE TITLE
problem encountered running demo.py

### ISSUE THREAD

**Issue by msqiqi10** [abojchevski/sparse_smoothing#1]
Thanks for your contribution!

When I was trying to incorporate your work as a baseline, I'm having this error:
In `sparse_smoothing/models.py`, line 18 `edge_idx, norm = self.norm(edge_idx, x.size(0), None, self.improved, x.dtype)`
`'SparseGCNConv' object has no attribute 'norm'`.
Could you please help me out?

Thanks!

**Comment by abojchevski** [comment]
Hi,

In the new version of Pytorch Geometric the way the normalization term for GCN models is computed was changed. I've updated the model to match the new version. Does it work for you now?
